name: The Tor Project Blog
title: The Tor Project Blog
email: contact@torproject.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog"
url: "http://tor.jmtodaro.com/blog/"
twitter_username: jekyllrb
github_username:  jekyll

markdown: redcarpet
highlighter: "pygments"
permalink: date

paginate: 5
paginate_path: "blog/page:num"
paginate_category: "blog"

sass:
  sass_dir: _sass
  style: :compressed

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
