name: The Tor Project Blog
title: The Tor Project Blog
email: contact@torproject.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://torblog.lan/"
twitter_username: jekyllrb
github_username:  jekyll

markdown: redcarpet
highlighter: "pygments"
permalink: date

paginate: 5
paginate_path: "blog/page:num"
paginate_category: "blog"

sass:
  sass_dir: _sass
  style: :compressed

jekyll-archives:
  layout: 'archive'
  enabled:
    - year
    - month
    - day
    - tags
    - categories
  layouts:
    year: 'archive-year'
    month: 'archive-month'
    day: 'archive-day'
    tag: 'archive-tag-and-category'
    category: 'archive-tag-and-category'
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    day: '/archive/:year/:month/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

gems:
  - jekyll-archives